variable "region" {}
variable "project-name" {}
variable "vpc-cidr" {}
variable "pub-sub-az1-cidr" {}
variable "pub-sub-az2-cidr" {}
variable "pvt-sub-az1-cidr" {}
variable "pvt-sub-az2-cidr" {}
variable "pvt-data-sub-az1-cidr" {}
variable "pvt-data-sub-az2-cidr" {}
variable "security-group" {}